# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculation of exp{W(tj, b)}
#'
#' @keywords internal
expWArma <- function(imat_, zt_, b_, gam) {
    .Call('joineRML_expWArma', PACKAGE = 'joineRML', imat_, zt_, b_, gam)
}

#' Calculation of E[exp{W(tj, b)}]
#'
#' @keywords internal
EexpWArma <- function(w_, f_, d_) {
    .Call('joineRML_EexpWArma', PACKAGE = 'joineRML', w_, f_, d_)
}

#' Newton-Raphson updates of gamma (E-step and M-step) using an empirical
#' infomration matrix approximation
#'
#' @keywords internal
gammaUpdate_approx <- function(b_, z_, w_, f_, d_, haz, v_, h_, K, q, nev) {
    .Call('joineRML_gammaUpdate_approx', PACKAGE = 'joineRML', b_, z_, w_, f_, d_, haz, v_, h_, K, q, nev)
}

#' Newton-Raphson updates of gamma (E-step and M-step) using an exact observed
#' information calculation
#'
#' @keywords internal
gammaUpdate <- function(b_, z_, w_, f_, d_, haz, v_, h_, K, q, nev) {
    .Call('joineRML_gammaUpdate', PACKAGE = 'joineRML', b_, z_, w_, f_, d_, haz, v_, h_, K, q, nev)
}

#' lambda0(t) for profile score function of beta
#'
#' @keywords internal
hazHat <- function(w_, f_, d_, nev) {
    .Call('joineRML_hazHat', PACKAGE = 'joineRML', w_, f_, d_, nev)
}

#' Updates of lambda0 (E-step and M-step)
#'
#' @keywords internal
lambdaUpdate <- function(b_, imat_, zt_, f_, v_, d_, gam, gam_vec, q, nev, h_) {
    .Call('joineRML_lambdaUpdate', PACKAGE = 'joineRML', b_, imat_, zt_, f_, v_, d_, gam, gam_vec, q, nev, h_)
}

#' Antithetic simulation of MVN random variables
#'
#' @keywords internal
mvrnormArma <- function(n, mu, sigma) {
    .Call('joineRML_mvrnormArma', PACKAGE = 'joineRML', n, mu, sigma)
}

#' Get a list of MVN samples for each subject
#'
#' @keywords internal
bSim <- function(n, Mean_, Sigma_) {
    .Call('joineRML_bSim', PACKAGE = 'joineRML', n, Mean_, Sigma_)
}

